= CQ Package Plugin
:toc:
:toc-placement!:
:toc-title:

toc::[]

== Usage

`apply plugin: "com.twcable.cq-package"`

The standard Gradle "base" plugin is automatically applied and the .zip created by `createPackage` is added to
the list of artifacts.

There is link:../../../issues/12[a plan to provide example projects and build files]. In the mean time, the link:../src/test/groovy/com/twcable/gradle/cqpackage/[test cases show explicitly how everything is expected to be used], in particular link:../src/test/groovy/com/twcable/gradle/cqpackage/CqPackagePluginIntSpec.groovy[CqPackagePluginIntSpec creates stub projects and associated build files].

== Tasks

=== Working Directly With Packages

[horizontal]
--
createPackage::
  This will create the `.zip` files that encapsulates a CQ Package file. It extends the `Zip` Gradle task, adding
  special features to make it easier to work with for the specifics that CQ wants.
+
See <<task-createpackage,the much more complete list of features below>>.


uploadPackage::
  Upload the package to all the servers defined by the `slingServers` configuration. This merely uploads the package
  into Package Manager -- it does not automatically do the "install".
+
If the package already exists (even as a "-SNAPSHOT"), you probably want to uninstall and remove it before
uploading a new one. See
http://blog.mooregreatsoftware.com/2015/07/21/aem-6-dot-1-packages-and-bundles-installing-and-uninstalling-behavior/[AEM 6.1 Packages and Bundles - Installing and Uninstalling Behavior]
for much more information on why. For that reason it depends on `removePackage` by default.
+
See <<task-uploadpackage,the `uploadPackage` configuration below>>, as well https://github.com/TWCable/gradle-plugin-cq-bundle/blob/master/docs/CqBundlePlugin.adoc#convention-slingservers[as `slingServers`].


installPackage::
  Installs the CQ Package that has been uploaded.
+
Does not include uploading the package, so depending on your workflow you might want to do that first.
+
Uses the name of the project as the name of the package. See below.


uninstallPackage::
  Uninstalls the CQ Package. **If the package is not on the server, nothing happens.**
  (i.e., This does not fail if the package is not on the server.)


removePackage::
  Removes the package from CQ. **Does not fail if the package was not on the server to begin with.**
+
This depends on `uninstallPackage` so that the old content is not left behind.

--

=== Working With Bundles In Packages

[horizontal]
--

validateBundles::
  Checks all the JARs that are included in this package to make sure they are installed and in an
  ACTIVE state. Gives a report of any that are not. This task polls using
  https://github.com/TWCable/gradle-plugin-cq-bundle/blob/master/docs/CqBundlePlugin.adoc#convention-slingservers[the
  server settings for retries and max time] in the case the bundles are newly installed.


validateRemoteBundles::
  The same as `validateBundles` but downloads the package as it exists on the remote server, then extracts it to get
  the bundles inside it. Useful in those situations where the "current" version of the package's list of bundles is
  potentially different than what is installed on the server.

uninstallBundles::
  Downloads the currently installed package .zip file if it exists, compiles a list of bundles
  based off what is currently installed, then stops and uninstalls each bundles individually.
+
This currently does not take dependency ordering into account. See https://github.com/TWCable/gradle-plugin-cq-package/issues/14[GH-14].

--

=== Support Tasks

[horizontal]
--

addBundlesToFilterXml::
  Adds the bundles to the `filter.xml`

verifyBundles::
  Checks all the JARs that are included in this package to make sure they are OSGi compliant, and
  gives a report of any that are not. Never causes the build to fail.

startInactiveBundles::
  Asynchronously attempts to start any bundle in RESOLVED state.
--

Of course, if any of the automatically depended-upon tasks are not desired for any reason, simply disable
it in your build file or with the `-x` command line option.


== Configuration

=== Convention: `slingServers`

This uses https://github.com/TWCable/gradle-plugin-cq-bundle/blob/master/docs/CqBundlePlugin.adoc#ways-of-configuring-slingservers[the `slingServers` configuration brought over from gradle-plugin-cq-bundle].

[[task-uploadpackage]]
== Task `uploadPackage`

=== Configuration

It can be useful to use an existing file rather than the output of `createPackage`.
(e.g., In a deployment pipeline where the artifact is pulled from a repository.)
Setting the `package` system property (i.e., `-Dpackage=XX`) will force the
use of the specified file.

This will fail if it doesn't have a file to upload, either because `createPackage` has not been run or the `package`
system property has not been set.


== Task `uninstallBundles`

Downloads the currently installed package .zip file if it exists, compiles list of bundles based off what is
currently installed, then stops and uninstalls each bundle individually.

=== Configuration

[horizontal]
uninstallBundlesPredicate::
  A predicate that takes in a bundle's symbolic name and returns true if it should be uninstalled. For example,
  `{ it.startsWith('com.mystuff') }` will limit the scope to only those bundles starting with "com.mystuff".
  **Defaults to always being `true`, so every bundle in the package will be uninstalled**



[[task-createpackage]]
== Task `createPackage`

=== Features

Inclusion of bundles to install::
  By default any OSGi bundles that are depended upon by the project will be copied into the /apps/install folder to be
  https://sling.apache.org/documentation/bundles/jcr-installer-provider.html[automatically installed by Sling upon package installation].

Variable substitution of `META-INF/vault/definition/.content.xml` and `META-INF/vault/properties.xml`::
  The source files will be treated as templates with the Project properties passed in for substitution. Particularly
  useful for things like `${version}`.+++<br/>+++
  *NOTE:* There's currently a dependency for the `install` task between the project name (`project.name`) and the
  `"name"` values in these metadata files. See issue #24.

Explicit inclusion of bundles in `filter.xml`::
  Each of the bundles installed by the package receive their own `<filter/>` line in `filter.xml` to ensure that
  it gets cleanly removed upon package uninstallation without stepping on bundles that other packages may
  have installed. (Done via the `addBundlesToFilterXml` task, which uses the configuration of `createPackage`.)

=== Configuration

[horizontal]
bundleInstallRoot::
  Where to install included bundles in the JCR. **Defaults to `"/apps/install"`**

contentSrc::
  The filesystem location to act as the top-level of the content to put in the package.
  **Defaults to project.file("src/main/content")**

fileExclusions::
  Mutable list of common exclusions such as ++"**/.vlt", "**/.git/**"++, etc.
  Generally to modify this list you would mutate this in-place.

addAllBundles()::
  All the bundles that this depends on (project and non-project) will be copied into the _bundleInstallRoot_.
  **This is the default behavior.**

addProjectBundles()::
  Only the project-generated bundles that this depends on will be copied into
  the _bundleInstallRoot_.

addNonProjectBundles()::
  Only the non-project generated bundles that this depends on be will copied into
  the _bundleInstallRoot_.

addNoBundles()::
  None of the bundles that this depends on will be copied into the _bundleInstallRoot_.


==== Example usage

[source,groovy]
--
createPackage {
    addProjectBundles()
}
--

=== Dependency Configuration: `cq_package`

`cq_package` extends the `runtime` configuration, if it exists.

Example usage:

[source,groovy]
--
dependencies {
    compile project(':project-name')
    compile "net.tanesha:recaptcha4j:1.0.0"
}

configurations.cq_package {
    exclude group: 'javax.servlet', module: 'servlet-api'
}
--
